name:                reflex-glfw
version:             0.1.6.0
github:              burningwitness/reflex-glfw
license:             BSD3
license-file:        LICENSE
author:              Oleksii Divak
maintainer:          Oleksii Divak <frozenwitness@gmail.com>
copyright:           (c) 2021, Oleksii Divak

extra-source-files:
- README.md

synopsis:            Reflex FRP host based on GLFW
category:            FRP

description:         Please see the README on GitHub at <https://github.com/burningwitness/reflex-glfw#readme>

dependencies:
- base >= 4.9 && < 5
- bifunctors
- containers
- dependent-map
- dependent-sum
- dependent-sum-template
- GLFW-b >= 3.2 && < 4
- reflex
- ref-tf
- stm

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  framerate:
    main:                Framerate.hs
    source-dirs:         test/framerate
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is Framerate
    dependencies:
    - ansi-terminal
    - bytestring
    - dependent-map
    - dependent-sum-template
    - OpenGL
    - reflex-glfw
    - vector
    - witherable

  physics:
    main:                Physics.hs
    source-dirs:         test/physics
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is Physics
    dependencies:
    - ansi-terminal
    - dependent-map
    - dependent-sum-template
    - OpenGL
    - reflex-glfw
    - witherable

  context:
    main:                Context.hs
    source-dirs:         test/context
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is Context
    dependencies:
    - gl
    - reflex-glfw
